[versions]
agp = "8.7.3"
coordinatorlayout = "1.3.0"
core = "1.7.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
lifecycleLivedataKtx = "2.10.0"
lifecycleViewmodelKtx = "2.10.0"
mockitoCore = "5.5.0"
navigationFragment = "2.9.6"
navigationUi = "2.9.6"
robolectric = "4.11.1"
roomCompiler = "2.8.4"
roomRuntime = "2.8.4"
runner = "1.7.0"

[libraries]
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-rules = { module = "androidx.test:rules", version.ref = "runner" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

